/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LupaPasswordRouteImport } from './routes/lupa-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as JaringanRouteImport } from './routes/jaringan'
import { Route as DaftarRouteImport } from './routes/daftar'
import { Route as IndexRouteImport } from './routes/index'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LupaPasswordRoute = LupaPasswordRouteImport.update({
  id: '/lupa-password',
  path: '/lupa-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const JaringanRoute = JaringanRouteImport.update({
  id: '/jaringan',
  path: '/jaringan',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarRoute = DaftarRouteImport.update({
  id: '/daftar',
  path: '/daftar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/jaringan': typeof JaringanRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/login': typeof LoginRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/jaringan': typeof JaringanRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/login': typeof LoginRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daftar': typeof DaftarRoute
  '/jaringan': typeof JaringanRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/login': typeof LoginRoute
  '/lupa-password': typeof LupaPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daftar'
    | '/jaringan'
    | '/kontak'
    | '/layanan'
    | '/login'
    | '/lupa-password'
    | '/sitemap.xml'
    | '/tentang'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daftar'
    | '/jaringan'
    | '/kontak'
    | '/layanan'
    | '/login'
    | '/lupa-password'
    | '/sitemap.xml'
    | '/tentang'
  id:
    | '__root__'
    | '/'
    | '/daftar'
    | '/jaringan'
    | '/kontak'
    | '/layanan'
    | '/login'
    | '/lupa-password'
    | '/sitemap.xml'
    | '/tentang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DaftarRoute: typeof DaftarRoute
  JaringanRoute: typeof JaringanRoute
  KontakRoute: typeof KontakRoute
  LayananRoute: typeof LayananRoute
  LoginRoute: typeof LoginRoute
  LupaPasswordRoute: typeof LupaPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TentangRoute: typeof TentangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lupa-password': {
      id: '/lupa-password'
      path: '/lupa-password'
      fullPath: '/lupa-password'
      preLoaderRoute: typeof LupaPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jaringan': {
      id: '/jaringan'
      path: '/jaringan'
      fullPath: '/jaringan'
      preLoaderRoute: typeof JaringanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar': {
      id: '/daftar'
      path: '/daftar'
      fullPath: '/daftar'
      preLoaderRoute: typeof DaftarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DaftarRoute: DaftarRoute,
  JaringanRoute: JaringanRoute,
  KontakRoute: KontakRoute,
  LayananRoute: LayananRoute,
  LoginRoute: LoginRoute,
  LupaPasswordRoute: LupaPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TentangRoute: TentangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
